FROM resin/%%RESIN_MACHINE_NAME%%-python:3.6.2

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . ./

ENV INITSYSTEM on

ENV FLASK_APP src/app.py
ENV FLASK_DEBUG 1

CMD ["flask", "run", "--host=0.0.0.0"]
